name: Nix Browser Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            python3 \
            python3-pip \
            git \
            curl \
            nodejs \
            npm \
            libglib2.0-dev \
            libgtk-3-dev \
            libnss3-dev \
            libxss-dev \
            libasound2-dev

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Packages
        run: npm install

      - name: Build Linux
        run: |
          npm run create_dist

      - name: Upload .deb File
        uses: actions/upload-artifact@v3
        with:
          name: nix-browser-linux
          path: |
            out/Release/*.deb
            out/Release/*.rpm
